### PR TITLE
Added Symfony 4.0.x support

### PR DESCRIPTION
**Pull request by netbull**

### CODE REVIEW

**Comment by xabbuh** [comment]
This looks like a duplicate of #121. :)

**Comment by netbull** [comment]
except there are actual changes to the code :)

**Comment by netbull** [comment]
@suncat2000 ping...

**Comment by bocharsky-bw** [comment]
This PR should be rebased, I see it has merge conflicts which should be fixed first

**Comment by abarke** [comment]
Does anyone want to finalize this pls?

**Comment by alexhoma** [comment]
Hi, what is the status of this issue?

**Comment by thomaspicquet** [comment]
I'm going to assume this bundle isn't maintained anymore?

**Pull request closed without merging**
