### PR TITLE
Update composer.json to allow Twig v2 to be used

### PR DESCRIPTION
**Pull request by netbull**

### CODE REVIEW

**Comment by grizzlylab** [comment]
Thank you !  😄

**Comment by netbull** [comment]
:)

**Comment by suncat2000** [comment]
@netbull, @grizzlylab tagged in https://github.com/suncat2000/MobileDetectBundle/tree/v1.0.4

**Comment by suncat2000** [comment]
@netbull Thanx!

**Comment by xabbuh** [comment]
@suncat2000 @netbull Is there actually a reason you are implementing the `\Twig_Extension_GlobalsInterface`?

**Comment by netbull** [comment]
@suncat2000 the bundle deserves maintenance

@xabbuh is did't implemented this interface. In Twig v1 is actually empty interface who know why it was there, but in v2 is with getGlobals function... again who knows why is there. I think is not necessary to implement it at all.

**Comment by suncat2000** [comment]
@xabbuh I am not remember now, but this interface I added when implement sf3.0 support. I recheck now and remove if it is possible.

**Comment by netbull** [comment]
@suncat2000 I think it's not needed

**Comment by suncat2000** [comment]
@xabbuh, @netbull removed in https://github.com/suncat2000/MobileDetectBundle/tree/v1.0.5.
Thanks guys!

**Comment by xabbuh** [comment]
Thanks for the fast reaction @suncat2000!

**Pull request merged**
